### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-buscadores-de-datos#1]
[REPORTE PRACTICA 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-buscadores-de-datos/files/14317633/REPORTE.PRACTICA.3.pdf)

*Ariadna Monserrat Lòpez Aparicio
*Roldan Uriel Arcadio Avila
*Pedro Garcia Garcia

**Comment by Anakimberly** [comment]
97/100 
Tiene errores en algunas palabras, específicamente en acentos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
